### ISSUE TITLE
pok3rconf fails to build on g++ 4.8

### ISSUE THREAD

**Issue by jpeirce** [pok3r-custom/Pok3rConf#1]
Needs to pass flags -std=gnu++11 or c++11.

```
[ 80%] Built target pok3rlib
[ 82%] Generating qrc_resource.cpp
[ 84%] Generating ui_mainwindow.h
[ 86%] Generating ui_keycustomize.h
Scanning dependencies of target pok3rconf
[ 88%] Building CXX object CMakeFiles/pok3rconf.dir/main.cpp.o
In file included from /home/jack/src/pok3rconf/pok3rtool/libchaos/chaos/string/zstring.h:9:0,
                 from /home/jack/src/pok3rconf/mainworker.h:8,
                 from /home/jack/src/pok3rconf/mainwindow.h:4,
                 from /home/jack/src/pok3rconf/main.cpp:1:
/home/jack/src/pok3rconf/pok3rtool/libchaos/chaos/./ztypes.h:23:6: error: #error LibChaos requires a C++11 compiler!
```

Looking into this, simplest solution would be to force set cmake_minimum_required to 3.1 and set(CMAKE_CXX_STANDARD 11).

However, doing so, it still fails to compile:
```
[ 80%] Built target pok3rlib
[ 82%] Generating qrc_resource.cpp
[ 84%] Generating ui_mainwindow.h
[ 86%] Generating ui_keycustomize.h
Scanning dependencies of target pok3rconf
[ 88%] Building CXX object CMakeFiles/pok3rconf.dir/main.cpp.o
[ 88%] Building CXX object CMakeFiles/pok3rconf.dir/mainwindow.cpp.o
[ 90%] Building CXX object CMakeFiles/pok3rconf.dir/mainworker.cpp.o
/home/jack/src/pok3rconf/mainworker.cpp:6:15: error: missing binary operator before token "("
 #if !QT_CONFIG(ssl)
```
Unfortunately, I was not able to figure this one out, I do believe I have all necessary QT dependencies.

**Comment by ChaoticEnigma** [comment]
Interesting, on gcc 4.8 i added `set_property(TARGET pok3rconf PROPERTY CXX_STANDARD 11)`, and it compiles for me, but I get a linker error that looks like the Qt libraries linking C++14 standard library features. So at least as built on Arch Linux, Qt doesn't support gcc 4.8

**Comment by jpeirce** [comment]
I get about the same error on gcc/g++ 5.3.1/6.2.1/7.3.1
/home/jack/src/pok3rconf/mainworker.cpp:6:15: error: missing binary operator before token "("
 #if !QT_CONFIG(ssl)

This is on OpenSUSE 42.3.

I will look into this more later today, perhaps I am missing some library

**Comment by jpeirce** [comment]
FWIW it compiles fine if you comment out the check for SSL.
Lack of documentation has held me back from attempting to actually flash my board.

I'm upgrading my system to the newer version of OpenSuSe today, will see if that makes any difference.

**Comment by jpeirce** [comment]
Updated to OpenSUSE 15 and there is no longer an error.
15 now uses 7.3.1 as the default compiler, as opposed to 4.8.5 for the previous release 42.3. gcc4/5/6 are not even available in the repos, though there is a possibility that is due to my upgrade method.

Unsure if you want to close this or not.

**Comment by ChaoticEnigma** [comment]
Hmm, qt must be using some compiler trick for that ssl check that 4.8 doesn't support. I'm not quite at the point where I need to determine which distros/versions I need to support, but I'll keep this in mind.

As for documentation, I've been holding back until I'm confident the firmware for each supported keyboard won't make the keyboard a brick. If I made it too easy to soon, I know people will try flashing unstable firmware.

**Comment by jpeirce** [comment]
I got the same error on gcc/g++ 7.3.1 on the older OpenSUSE, so I don't think it's just a compiler issue. Maybe some optional qt package got rolled into base or the old version had an incomplete package.
